= Cloudberry Pi Technologies
:toc:
:sectnums:
:author: Cloudberry Pi Foundations

Create masterpieces at the touch of a button

== Projects
=== Programming Softwares & Languages
.The languages that we can code in are:
[%collapsible]
====

. Scratch
. Python
. Javascript
. HTML
. AppleScript
. CSS
. Java
. C++
. C
. Kotlin
. Asciidoctor
. Markdown

====

.The softwares we can program in are:
[%collapsible]
====

. Scratch
. IntelliJ Idea
. Jetbrains Pycharm
. Jetbrains RubyMine
. Jetbrains Webstorm
. Visual Studio Code
. AppleScript Editor
. Notepad
. Notepad ++
. Github Online Editor

====

== Build Quality
Each build is double checked as well as debugged before commiting, except for a few commits, most of the softwares uploaded are bug free.
Every build is tested on Windows, Mac, Linux and Raspbian Trixie and is listed with the compatible operating systems, if none are written then it is compatible with MacOS, Linux and Raspbian Trixie.
For adding your projects to our repositories please visit our https://forms.cloud.microsoft/r/9W6uFBHFn7[Repo Feedback Page].

== Thank You
Thank you for visiting our repo, if you like this, please follow and star your favorite repo.
Your support helps us develop software better.
